sonar.projectKey=c-d-p_uni-71Cdevsecops
sonar.organization=c-d-p
sonar.host.url=https://sonarcloud.io
sonar.login=e163ca220071bc300120ba22d7e35b98b7308960
sonar.sources=.
sonar.exclusions=node_modules/**,test/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.projectName=uni-71Cdevsecops
sonar.sourceEncoding=UTF-8